package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Businesstype generated by hbm2java
 */
public class Businesstype  implements java.io.Serializable {


     private Integer businessTypeId;
     private String businessType;
     private Set businesses = new HashSet(0);

    public Businesstype() {
    }

	
    public Businesstype(String businessType) {
        this.businessType = businessType;
    }
    public Businesstype(String businessType, Set businesses) {
       this.businessType = businessType;
       this.businesses = businesses;
    }
   
    public Integer getBusinessTypeId() {
        return this.businessTypeId;
    }
    
    public void setBusinessTypeId(Integer businessTypeId) {
        this.businessTypeId = businessTypeId;
    }
    public String getBusinessType() {
        return this.businessType;
    }
    
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }
    public Set getBusinesses() {
        return this.businesses;
    }
    
    public void setBusinesses(Set businesses) {
        this.businesses = businesses;
    }




}


