package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Business generated by hbm2java
 */
public class Business  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Businesstype businesstype;
	private String businessId;
	private String name;
	private String websiteUrl;
	private Boolean isClaimed;
	private Boolean isClosed;
	private String mobileUrl;
	private String phone;
	private String displayPhone;
	private String reviewCount;
	private Long distance;
	private Double rating;
	private String ratingImgUrl;
	private String ratingSmallImgUrl;
	private String ratingLargeImgUrl;
	private String snippetText;
	private String snippetImageUrl;
	private String menuProvider;
	private Long menuProviderDate;
	private String crossStreets;
	private String city;
	private String displayAddress;
	private String postalCode;
	private String countryCode;
	private String address;
	private String stateCode;
	private String neighborhoods;
	private String lattitude;
	private String longitude;
	private String ambience;
	private Boolean isParkingAvailable;
	private String traffic;
	private String serviceLevel;
	private String noiseLevel;
	private String likeCount;
	private Boolean isActive;
	private String imageUrl;
	private String workingHours;
	private String musicType;
	private String source;
	private String state;
	private Set reviews = new HashSet(0);
	private Set foodmenuitems = new HashSet(0);
	private Set dealses = new HashSet(0);
	private Set pages = new HashSet(0);
	private Set usernondealsuggestions = new HashSet(0);
	private Set topnondealsuggestions = new HashSet(0);

	public Business() {
	}


	public Business(Businesstype businesstype) {
		this.businesstype = businesstype;
	}
	public Business(Businesstype businesstype, String businessId, String name, String websiteUrl, Boolean isClaimed, Boolean isClosed, String mobileUrl, String phone, String displayPhone, String reviewCount, Long distance, Double rating, String ratingImgUrl, String ratingSmallImgUrl, String ratingLargeImgUrl, String snippetText, String snippetImageUrl, String menuProvider, Long menuProviderDate, String crossStreets, String city, String displayAddress, String postalCode, String countryCode, String address, String stateCode, String neighborhoods, String lattitude, String longitude, String ambience, Boolean isParkingAvailable, String traffic, String serviceLevel, String noiseLevel, String likeCount, Boolean isActive, String imageUrl, String workingHours, String musicType, Set reviews, Set foodmenuitems, Set dealses, Set pages, Set usernondealsuggestions, Set topnondealsuggestions) {
		this.businesstype = businesstype;
		this.businessId = businessId;
		this.name = name;
		this.websiteUrl = websiteUrl;
		this.isClaimed = isClaimed;
		this.isClosed = isClosed;
		this.mobileUrl = mobileUrl;
		this.phone = phone;
		this.displayPhone = displayPhone;
		this.reviewCount = reviewCount;
		this.distance = distance;
		this.rating = rating;
		this.ratingImgUrl = ratingImgUrl;
		this.ratingSmallImgUrl = ratingSmallImgUrl;
		this.ratingLargeImgUrl = ratingLargeImgUrl;
		this.snippetText = snippetText;
		this.snippetImageUrl = snippetImageUrl;
		this.menuProvider = menuProvider;
		this.menuProviderDate = menuProviderDate;
		this.crossStreets = crossStreets;
		this.city = city;
		this.displayAddress = displayAddress;
		this.postalCode = postalCode;
		this.countryCode = countryCode;
		this.address = address;
		this.stateCode = stateCode;
		this.neighborhoods = neighborhoods;
		this.lattitude = lattitude;
		this.longitude = longitude;
		this.ambience = ambience;
		this.isParkingAvailable = isParkingAvailable;
		this.traffic = traffic;
		this.serviceLevel = serviceLevel;
		this.noiseLevel = noiseLevel;
		this.likeCount = likeCount;
		this.isActive = isActive;
		this.imageUrl = imageUrl;
		this.workingHours = workingHours;
		this.musicType = musicType;
		this.reviews = reviews;
		this.foodmenuitems = foodmenuitems;
		this.dealses = dealses;
		this.pages = pages;
		this.usernondealsuggestions = usernondealsuggestions;
		this.topnondealsuggestions = topnondealsuggestions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}
	public Businesstype getBusinesstype() {
		return this.businesstype;
	}

	public void setBusinesstype(Businesstype businesstype) {
		this.businesstype = businesstype;
	}
	public String getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	public String getWebsiteUrl() {
		return this.websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}
	public Boolean getIsClaimed() {
		return this.isClaimed;
	}

	public void setIsClaimed(Boolean isClaimed) {
		this.isClaimed = isClaimed;
	}
	public Boolean getIsClosed() {
		return this.isClosed;
	}

	public void setIsClosed(Boolean isClosed) {
		this.isClosed = isClosed;
	}
	public String getMobileUrl() {
		return this.mobileUrl;
	}

	public void setMobileUrl(String mobileUrl) {
		this.mobileUrl = mobileUrl;
	}
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getDisplayPhone() {
		return this.displayPhone;
	}

	public void setDisplayPhone(String displayPhone) {
		this.displayPhone = displayPhone;
	}
	public String getReviewCount() {
		return this.reviewCount;
	}

	public void setReviewCount(String reviewCount) {
		this.reviewCount = reviewCount;
	}
	public Long getDistance() {
		return this.distance;
	}

	public void setDistance(Long distance) {
		this.distance = distance;
	}
	public Double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}
	public String getRatingImgUrl() {
		return this.ratingImgUrl;
	}

	public void setRatingImgUrl(String ratingImgUrl) {
		this.ratingImgUrl = ratingImgUrl;
	}
	public String getRatingSmallImgUrl() {
		return this.ratingSmallImgUrl;
	}

	public void setRatingSmallImgUrl(String ratingSmallImgUrl) {
		this.ratingSmallImgUrl = ratingSmallImgUrl;
	}
	public String getRatingLargeImgUrl() {
		return this.ratingLargeImgUrl;
	}

	public void setRatingLargeImgUrl(String ratingLargeImgUrl) {
		this.ratingLargeImgUrl = ratingLargeImgUrl;
	}
	public String getSnippetText() {
		return this.snippetText;
	}

	public void setSnippetText(String snippetText) {
		this.snippetText = snippetText;
	}
	public String getSnippetImageUrl() {
		return this.snippetImageUrl;
	}

	public void setSnippetImageUrl(String snippetImageUrl) {
		this.snippetImageUrl = snippetImageUrl;
	}
	public String getMenuProvider() {
		return this.menuProvider;
	}

	public void setMenuProvider(String menuProvider) {
		this.menuProvider = menuProvider;
	}
	public Long getMenuProviderDate() {
		return this.menuProviderDate;
	}

	public void setMenuProviderDate(Long menuProviderDate) {
		this.menuProviderDate = menuProviderDate;
	}
	public String getCrossStreets() {
		return this.crossStreets;
	}

	public void setCrossStreets(String crossStreets) {
		this.crossStreets = crossStreets;
	}
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}
	public String getDisplayAddress() {
		return this.displayAddress;
	}

	public void setDisplayAddress(String displayAddress) {
		this.displayAddress = displayAddress;
	}
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}
	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}
	public String getNeighborhoods() {
		return this.neighborhoods;
	}

	public void setNeighborhoods(String neighborhoods) {
		this.neighborhoods = neighborhoods;
	}
	public String getLattitude() {
		return this.lattitude;
	}

	public void setLattitude(String lattitude) {
		this.lattitude = lattitude;
	}
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}
	public String getAmbience() {
		return this.ambience;
	}

	public void setAmbience(String ambience) {
		this.ambience = ambience;
	}
	public Boolean getIsParkingAvailable() {
		return this.isParkingAvailable;
	}

	public void setIsParkingAvailable(Boolean isParkingAvailable) {
		this.isParkingAvailable = isParkingAvailable;
	}
	public String getTraffic() {
		return this.traffic;
	}

	public void setTraffic(String traffic) {
		this.traffic = traffic;
	}
	public String getServiceLevel() {
		return this.serviceLevel;
	}

	public void setServiceLevel(String serviceLevel) {
		this.serviceLevel = serviceLevel;
	}
	public String getNoiseLevel() {
		return this.noiseLevel;
	}

	public void setNoiseLevel(String noiseLevel) {
		this.noiseLevel = noiseLevel;
	}
	public String getLikeCount() {
		return this.likeCount;
	}

	public void setLikeCount(String likeCount) {
		this.likeCount = likeCount;
	}
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}
	public String getWorkingHours() {
		return this.workingHours;
	}

	public void setWorkingHours(String workingHours) {
		this.workingHours = workingHours;
	}
	public String getMusicType() {
		return this.musicType;
	}

	public void setMusicType(String musicType) {
		this.musicType = musicType;
	}
	public Set getReviews() {
		return this.reviews;
	}

	public void setReviews(Set reviews) {
		this.reviews = reviews;
	}
	public Set getFoodmenuitems() {
		return this.foodmenuitems;
	}

	public void setFoodmenuitems(Set foodmenuitems) {
		this.foodmenuitems = foodmenuitems;
	}
	public Set getDealses() {
		return this.dealses;
	}

	public void setDealses(Set dealses) {
		this.dealses = dealses;
	}
	public Set getPages() {
		return this.pages;
	}

	public void setPages(Set pages) {
		this.pages = pages;
	}


	public Set getUsernondealsuggestions() {
		return usernondealsuggestions;
	}


	public void setUsernondealsuggestions(Set usernondealsuggestions) {
		this.usernondealsuggestions = usernondealsuggestions;
	}


	/**
	 * @param source the source to set
	 */
	 public void setSource(String source) {
		this.source = source;
	}


	/**
	 * @return the source
	 */
	 public String getSource() {
		return source;
	}


	/**
	 * @param topnondealsuggestions the topnondealsuggestions to set
	 */
	 public void setTopnondealsuggestions(Set topnondealsuggestions) {
		this.topnondealsuggestions = topnondealsuggestions;
	}


	/**
	 * @return the topnondealsuggestions
	 */
	 public Set getTopnondealsuggestions() {
		return topnondealsuggestions;
	}


	/**
	 * @return the state
	 */
	 public String getState() {
		return state;
	}


	/**
	 * @param state the state to set
	 */
	 public void setState(String state) {
		this.state = state;
	}




}


