package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cuisinecategory generated by hbm2java
 */
public class Cuisinecategory  implements java.io.Serializable {


     private Integer cuisineCategoryId;
     private Cuisines cuisines;
     private String categoryName;
     private String puffery;
     private String description;
     private Set foodmenuitems = new HashSet(0);

    public Cuisinecategory() {
    }

	
    public Cuisinecategory(Cuisines cuisines) {
        this.cuisines = cuisines;
    }
    public Cuisinecategory(Cuisines cuisines, String categoryName, String puffery, String description, Set foodmenuitems) {
       this.cuisines = cuisines;
       this.categoryName = categoryName;
       this.puffery = puffery;
       this.description = description;
       this.foodmenuitems = foodmenuitems;
    }
   
    public Integer getCuisineCategoryId() {
        return this.cuisineCategoryId;
    }
    
    public void setCuisineCategoryId(Integer cuisineCategoryId) {
        this.cuisineCategoryId = cuisineCategoryId;
    }
    public Cuisines getCuisines() {
        return this.cuisines;
    }
    
    public void setCuisines(Cuisines cuisines) {
        this.cuisines = cuisines;
    }
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    public String getPuffery() {
        return this.puffery;
    }
    
    public void setPuffery(String puffery) {
        this.puffery = puffery;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getFoodmenuitems() {
        return this.foodmenuitems;
    }
    
    public void setFoodmenuitems(Set foodmenuitems) {
        this.foodmenuitems = foodmenuitems;
    }




}


