package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Foodmenuitem generated by hbm2java
 */
public class Foodmenuitem  implements java.io.Serializable {


     private Integer foodMenuItemId;
     private Cuisines cuisines;
     private Cuisinecategory cuisinecategory;
     private Business business;
     private String menuName;
     private String puffery;
     private Long price;
     private String currencyCode;
     private String formattedPrice;
     private Boolean isSpeciality;
     private Boolean isAvailable;
     private Boolean isLunchMenu;
     private Boolean isBurstMenu;
     private Boolean isDinnerMenu;

    public Foodmenuitem() {
    }

	
    public Foodmenuitem(Cuisines cuisines, Cuisinecategory cuisinecategory, Business business) {
        this.cuisines = cuisines;
        this.cuisinecategory = cuisinecategory;
        this.business = business;
    }
    public Foodmenuitem(Cuisines cuisines, Cuisinecategory cuisinecategory, Business business, String menuName, String puffery, Long price, String currencyCode, String formattedPrice, Boolean isSpeciality, Boolean isAvailable, Boolean isLunchMenu, Boolean isBurstMenu, Boolean isDinnerMenu) {
       this.cuisines = cuisines;
       this.cuisinecategory = cuisinecategory;
       this.business = business;
       this.menuName = menuName;
       this.puffery = puffery;
       this.price = price;
       this.currencyCode = currencyCode;
       this.formattedPrice = formattedPrice;
       this.isSpeciality = isSpeciality;
       this.isAvailable = isAvailable;
       this.isLunchMenu = isLunchMenu;
       this.isBurstMenu = isBurstMenu;
       this.isDinnerMenu = isDinnerMenu;
    }
   
    public Integer getFoodMenuItemId() {
        return this.foodMenuItemId;
    }
    
    public void setFoodMenuItemId(Integer foodMenuItemId) {
        this.foodMenuItemId = foodMenuItemId;
    }
    public Cuisines getCuisines() {
        return this.cuisines;
    }
    
    public void setCuisines(Cuisines cuisines) {
        this.cuisines = cuisines;
    }
    public Cuisinecategory getCuisinecategory() {
        return this.cuisinecategory;
    }
    
    public void setCuisinecategory(Cuisinecategory cuisinecategory) {
        this.cuisinecategory = cuisinecategory;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getPuffery() {
        return this.puffery;
    }
    
    public void setPuffery(String puffery) {
        this.puffery = puffery;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getFormattedPrice() {
        return this.formattedPrice;
    }
    
    public void setFormattedPrice(String formattedPrice) {
        this.formattedPrice = formattedPrice;
    }
    public Boolean getIsSpeciality() {
        return this.isSpeciality;
    }
    
    public void setIsSpeciality(Boolean isSpeciality) {
        this.isSpeciality = isSpeciality;
    }
    public Boolean getIsAvailable() {
        return this.isAvailable;
    }
    
    public void setIsAvailable(Boolean isAvailable) {
        this.isAvailable = isAvailable;
    }
    public Boolean getIsLunchMenu() {
        return this.isLunchMenu;
    }
    
    public void setIsLunchMenu(Boolean isLunchMenu) {
        this.isLunchMenu = isLunchMenu;
    }
    public Boolean getIsBurstMenu() {
        return this.isBurstMenu;
    }
    
    public void setIsBurstMenu(Boolean isBurstMenu) {
        this.isBurstMenu = isBurstMenu;
    }
    public Boolean getIsDinnerMenu() {
        return this.isDinnerMenu;
    }
    
    public void setIsDinnerMenu(Boolean isDinnerMenu) {
        this.isDinnerMenu = isDinnerMenu;
    }




}


