package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Gdeal generated by hbm2java
 */
public class Gdeal  implements java.io.Serializable {


     private Integer id;
     private Gmerchant gmerchant;
     private Gdivision gdivision;
     private String dealId;
     private String title;
     private String placementPriority;
     private String sidebarImageUrl;
     private String smallImageUrl;
     private String mediumImageUrl;
     private String largeImageUrl;
     private String announcementTitle;
     private String dealUrl;
     private String status;
     private Boolean isTipped;
     private Integer tippingPoint;
     private Boolean isSoldOut;
     private String soldQuantity;
     private Boolean shippingAddressRequired;
     private String highlightsHtml;
     private String pitchHtml;
     private String dealType;
     private Date startAt;
     private Date endAt;
     private Boolean isNowDeal;
     private Date tippedAt;
     private Set gdealoptions = new HashSet(0);
     private Set gtagses = new HashSet(0);
     private Set gdealtypes = new HashSet(0);

    public Gdeal() {
    }

	
    public Gdeal(Gmerchant gmerchant, Gdivision gdivision, String dealId) {
        this.gmerchant = gmerchant;
        this.gdivision = gdivision;
        this.dealId = dealId;
    }
    public Gdeal(Gmerchant gmerchant, Gdivision gdivision, String dealId, String title, String placementPriority, String sidebarImageUrl, String smallImageUrl, String mediumImageUrl, String largeImageUrl, String announcementTitle, String dealUrl, String status, Boolean isTipped, Integer tippingPoint, Boolean isSoldOut, String soldQuantity, Boolean shippingAddressRequired, String highlightsHtml, String pitchHtml, String dealType, Date startAt, Date endAt, Boolean isNowDeal, Date tippedAt, Set gdealoptions) {
       this.gmerchant = gmerchant;
       this.gdivision = gdivision;
       this.dealId = dealId;
       this.title = title;
       this.placementPriority = placementPriority;
       this.sidebarImageUrl = sidebarImageUrl;
       this.smallImageUrl = smallImageUrl;
       this.mediumImageUrl = mediumImageUrl;
       this.largeImageUrl = largeImageUrl;
       this.announcementTitle = announcementTitle;
       this.dealUrl = dealUrl;
       this.status = status;
       this.isTipped = isTipped;
       this.tippingPoint = tippingPoint;
       this.isSoldOut = isSoldOut;
       this.soldQuantity = soldQuantity;
       this.shippingAddressRequired = shippingAddressRequired;
       this.highlightsHtml = highlightsHtml;
       this.pitchHtml = pitchHtml;
       this.dealType = dealType;
       this.startAt = startAt;
       this.endAt = endAt;
       this.isNowDeal = isNowDeal;
       this.tippedAt = tippedAt;
       this.gdealoptions = gdealoptions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Gmerchant getGmerchant() {
        return this.gmerchant;
    }
    
    public void setGmerchant(Gmerchant gmerchant) {
        this.gmerchant = gmerchant;
    }
    public Gdivision getGdivision() {
        return this.gdivision;
    }
    
    public void setGdivision(Gdivision gdivision) {
        this.gdivision = gdivision;
    }
    public String getDealId() {
        return this.dealId;
    }
    
    public void setDealId(String dealId) {
        this.dealId = dealId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPlacementPriority() {
        return this.placementPriority;
    }
    
    public void setPlacementPriority(String placementPriority) {
        this.placementPriority = placementPriority;
    }
    public String getSidebarImageUrl() {
        return this.sidebarImageUrl;
    }
    
    public void setSidebarImageUrl(String sidebarImageUrl) {
        this.sidebarImageUrl = sidebarImageUrl;
    }
    public String getSmallImageUrl() {
        return this.smallImageUrl;
    }
    
    public void setSmallImageUrl(String smallImageUrl) {
        this.smallImageUrl = smallImageUrl;
    }
    public String getMediumImageUrl() {
        return this.mediumImageUrl;
    }
    
    public void setMediumImageUrl(String mediumImageUrl) {
        this.mediumImageUrl = mediumImageUrl;
    }
    public String getLargeImageUrl() {
        return this.largeImageUrl;
    }
    
    public void setLargeImageUrl(String largeImageUrl) {
        this.largeImageUrl = largeImageUrl;
    }
    public String getAnnouncementTitle() {
        return this.announcementTitle;
    }
    
    public void setAnnouncementTitle(String announcementTitle) {
        this.announcementTitle = announcementTitle;
    }
    public String getDealUrl() {
        return this.dealUrl;
    }
    
    public void setDealUrl(String dealUrl) {
        this.dealUrl = dealUrl;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Boolean getIsTipped() {
        return this.isTipped;
    }
    
    public void setIsTipped(Boolean isTipped) {
        this.isTipped = isTipped;
    }
    public Integer getTippingPoint() {
        return this.tippingPoint;
    }
    
    public void setTippingPoint(Integer tippingPoint) {
        this.tippingPoint = tippingPoint;
    }
    public Boolean getIsSoldOut() {
        return this.isSoldOut;
    }
    
    public void setIsSoldOut(Boolean isSoldOut) {
        this.isSoldOut = isSoldOut;
    }
    public String getSoldQuantity() {
        return this.soldQuantity;
    }
    
    public void setSoldQuantity(String soldQuantity) {
        this.soldQuantity = soldQuantity;
    }
    public Boolean getShippingAddressRequired() {
        return this.shippingAddressRequired;
    }
    
    public void setShippingAddressRequired(Boolean shippingAddressRequired) {
        this.shippingAddressRequired = shippingAddressRequired;
    }
    public String getHighlightsHtml() {
        return this.highlightsHtml;
    }
    
    public void setHighlightsHtml(String highlightsHtml) {
        this.highlightsHtml = highlightsHtml;
    }
    public String getPitchHtml() {
        return this.pitchHtml;
    }
    
    public void setPitchHtml(String pitchHtml) {
        this.pitchHtml = pitchHtml;
    }
    public String getDealType() {
        return this.dealType;
    }
    
    public void setDealType(String dealType) {
        this.dealType = dealType;
    }
    public Date getStartAt() {
        return this.startAt;
    }
    
    public void setStartAt(Date startAt) {
        this.startAt = startAt;
    }
    public Date getEndAt() {
        return this.endAt;
    }
    
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }
    public Boolean getIsNowDeal() {
        return this.isNowDeal;
    }
    
    public void setIsNowDeal(Boolean isNowDeal) {
        this.isNowDeal = isNowDeal;
    }
    public Date getTippedAt() {
        return this.tippedAt;
    }
    
    public void setTippedAt(Date tippedAt) {
        this.tippedAt = tippedAt;
    }
    public Set getGdealoptions() {
        return this.gdealoptions;
    }
    
    public void setGdealoptions(Set gdealoptions) {
        this.gdealoptions = gdealoptions;
    }


	public Set getGtagses() {
		return gtagses;
	}


	public void setGtagses(Set gtagses) {
		this.gtagses = gtagses;
	}


	public Set getGdealtypes() {
		return gdealtypes;
	}


	public void setGdealtypes(Set gdealtypes) {
		this.gdealtypes = gdealtypes;
	}




}


