package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Gdealprice generated by hbm2java
 */
public class Gdealprice  implements java.io.Serializable {


     private Integer id;
     private int amount;
     private String currencyCode;
     private String formattedAmount;
     private Set gdealoptionsForPriceId = new HashSet(0);
     private Set gdealoptionsForDiscountId = new HashSet(0);
     private Set gdealoptionsForValueId = new HashSet(0);

    public Gdealprice() {
    }

	
    public Gdealprice(int amount, String currencyCode) {
        this.amount = amount;
        this.currencyCode = currencyCode;
    }
    public Gdealprice(int amount, String currencyCode, String formattedAmount, Set gdealoptionsForPriceId, Set gdealoptionsForDiscountId, Set gdealoptionsForValueId) {
       this.amount = amount;
       this.currencyCode = currencyCode;
       this.formattedAmount = formattedAmount;
       this.gdealoptionsForPriceId = gdealoptionsForPriceId;
       this.gdealoptionsForDiscountId = gdealoptionsForDiscountId;
       this.gdealoptionsForValueId = gdealoptionsForValueId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getFormattedAmount() {
        return this.formattedAmount;
    }
    
    public void setFormattedAmount(String formattedAmount) {
        this.formattedAmount = formattedAmount;
    }
    public Set getGdealoptionsForPriceId() {
        return this.gdealoptionsForPriceId;
    }
    
    public void setGdealoptionsForPriceId(Set gdealoptionsForPriceId) {
        this.gdealoptionsForPriceId = gdealoptionsForPriceId;
    }
    public Set getGdealoptionsForDiscountId() {
        return this.gdealoptionsForDiscountId;
    }
    
    public void setGdealoptionsForDiscountId(Set gdealoptionsForDiscountId) {
        this.gdealoptionsForDiscountId = gdealoptionsForDiscountId;
    }
    public Set getGdealoptionsForValueId() {
        return this.gdealoptionsForValueId;
    }
    
    public void setGdealoptionsForValueId(Set gdealoptionsForValueId) {
        this.gdealoptionsForValueId = gdealoptionsForValueId;
    }




}


