package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Gdivision generated by hbm2java
 */
public class Gdivision  implements java.io.Serializable {


     private Integer id;
     private String divisionId;
     private String name;
     private String longitude;
     private String lattitude;
     private String timezone;
     private String timezoneOffsetInSeconds;     
     private String uuid;
     private Boolean isNowCustomerEnabled;
     private Boolean isPresenceEnabled;
     private String defaultLocale;
     private Boolean isReserveEnabled;
     private String timezoneIdentifier;
     private String country;
     private Boolean isNowMerchantEnabled;
     private Set gdeals = new HashSet(0);

    public Gdivision() {
    }

	
    public Gdivision(String divisionId) {
        this.divisionId = divisionId;        
    }
    public Gdivision(String divisionId, String name, String longitude, String lattitude, String timezone, String timezoneOffsetInSeconds, String uuid, Boolean isNowCustomerEnabled, Boolean isPresenceEnabled, String defaultLocale, Boolean isReserveEnabled, String timezoneIdentifier, String country, Boolean isNowMerchantEnabled, Set gdeals) {
       this.divisionId = divisionId;
       this.name = name;
       this.longitude = longitude;
       this.lattitude = lattitude;
       this.timezone = timezone;
       this.timezoneOffsetInSeconds = timezoneOffsetInSeconds;       
       this.uuid = uuid;
       this.isNowCustomerEnabled = isNowCustomerEnabled;
       this.isPresenceEnabled = isPresenceEnabled;
       this.defaultLocale = defaultLocale;
       this.isReserveEnabled = isReserveEnabled;
       this.timezoneIdentifier = timezoneIdentifier;
       this.country = country;
       this.isNowMerchantEnabled = isNowMerchantEnabled;
       this.gdeals = gdeals;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDivisionId() {
        return this.divisionId;
    }
    
    public void setDivisionId(String divisionId) {
        this.divisionId = divisionId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLattitude() {
        return this.lattitude;
    }
    
    public void setLattitude(String lattitude) {
        this.lattitude = lattitude;
    }
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }
    public String getTimezoneOffsetInSeconds() {
        return this.timezoneOffsetInSeconds;
    }
    
    public void setTimezoneOffsetInSeconds(String timezoneOffsetInSeconds) {
        this.timezoneOffsetInSeconds = timezoneOffsetInSeconds;
    }
    
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }
    public Boolean getIsNowCustomerEnabled() {
        return this.isNowCustomerEnabled;
    }
    
    public void setIsNowCustomerEnabled(Boolean isNowCustomerEnabled) {
        this.isNowCustomerEnabled = isNowCustomerEnabled;
    }
    public Boolean getIsPresenceEnabled() {
        return this.isPresenceEnabled;
    }
    
    public void setIsPresenceEnabled(Boolean isPresenceEnabled) {
        this.isPresenceEnabled = isPresenceEnabled;
    }
    public String getDefaultLocale() {
        return this.defaultLocale;
    }
    
    public void setDefaultLocale(String defaultLocale) {
        this.defaultLocale = defaultLocale;
    }
    public Boolean getIsReserveEnabled() {
        return this.isReserveEnabled;
    }
    
    public void setIsReserveEnabled(Boolean isReserveEnabled) {
        this.isReserveEnabled = isReserveEnabled;
    }
    public String getTimezoneIdentifier() {
        return this.timezoneIdentifier;
    }
    
    public void setTimezoneIdentifier(String timezoneIdentifier) {
        this.timezoneIdentifier = timezoneIdentifier;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Boolean getIsNowMerchantEnabled() {
        return this.isNowMerchantEnabled;
    }
    
    public void setIsNowMerchantEnabled(Boolean isNowMerchantEnabled) {
        this.isNowMerchantEnabled = isNowMerchantEnabled;
    }
    public Set getGdeals() {
        return this.gdeals;
    }
    
    public void setGdeals(Set gdeals) {
        this.gdeals = gdeals;
    }




}


