package com.jeeyoh.persistence.domain;
// Generated Nov 29, 2013 2:14:09 PM by Hibernate Tools 3.2.1.GA



/**
 * Gtags generated by hbm2java
 */
public class Gtags  implements java.io.Serializable {


     private Integer id;
     private Gdeal gdeal;
     private String name;

    public Gtags() {
    }

	
    public Gtags(Gdeal gdeal) {
        this.gdeal = gdeal;
    }
    public Gtags(Gdeal gdeal, String name) {
       this.gdeal = gdeal;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Gdeal getGdeal() {
        return this.gdeal;
    }
    
    public void setGdeal(Gdeal gdeal) {
        this.gdeal = gdeal;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


