package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Jeeyohgroup generated by hbm2java
 */
public class Jeeyohgroup  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer groupId;
     private User userByOwnerId;
     private Privacy privacy;
     private User userByCreatorId;
     private String groupName;
     private String about;
     private String groupType;
     private Date createdtime;
	 private Date updatedtime;    
     private Set groupusermaps = new HashSet(0);

    public Jeeyohgroup() {
    }

	
    public Jeeyohgroup(User userByOwnerId, Privacy privacy, User userByCreatorId, Date createdtime, Date updatedtime) {
        this.userByOwnerId = userByOwnerId;
        this.privacy = privacy;
        this.userByCreatorId = userByCreatorId;
        this.createdtime = createdtime;
        this.updatedtime = updatedtime;
    }
    public Jeeyohgroup(User userByOwnerId, Privacy privacy, User userByCreatorId, String groupName, String about, Date createdtime, Date updatedtime, Set groupusermaps) {
       this.userByOwnerId = userByOwnerId;
       this.privacy = privacy;
       this.userByCreatorId = userByCreatorId;
       this.groupName = groupName;
       this.about = about;
       this.createdtime = createdtime;
       this.updatedtime = updatedtime;
       this.groupusermaps = groupusermaps;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public User getUserByOwnerId() {
        return this.userByOwnerId;
    }
    
    public void setUserByOwnerId(User userByOwnerId) {
        this.userByOwnerId = userByOwnerId;
    }
    public Privacy getPrivacy() {
        return this.privacy;
    }
    
    public void setPrivacy(Privacy privacy) {
        this.privacy = privacy;
    }
    public User getUserByCreatorId() {
        return this.userByCreatorId;
    }
    
    public void setUserByCreatorId(User userByCreatorId) {
        this.userByCreatorId = userByCreatorId;
    }
    public String getGroupName() {
        return this.groupName;
    }
    
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }
    public Set getGroupusermaps() {
        return this.groupusermaps;
    }
    
    public void setGroupusermaps(Set groupusermaps) {
        this.groupusermaps = groupusermaps;
    }


	public void setGroupType(String groupType) {
		this.groupType = groupType;
	}


	public String getGroupType() {
		return groupType;
	}




}


