package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pagetype generated by hbm2java
 */
public class Pagetype  implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pageTypeId;
	private String pageType;
	private Set pages = new HashSet(0);

	public Pagetype() {
	}


	public Pagetype(String pageType) {
		this.pageType = pageType;
	}
	public Pagetype(String pageType, Set pages) {
		this.pageType = pageType;
		this.pages = pages;
	}

	public Integer getPageTypeId() {
		return this.pageTypeId;
	}

	public void setPageTypeId(Integer pageTypeId) {
		this.pageTypeId = pageTypeId;
	}
	public String getPageType() {
		return this.pageType;
	}

	public void setPageType(String pageType) {
		this.pageType = pageType;
	}
	public Set getPages() {
		return this.pages;
	}

	public void setPages(Set pages) {
		this.pages = pages;
	}




}


