package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Page generated by hbm2java
 */
public class Page  implements java.io.Serializable {


     private Integer pageId;
     private Pagetype pagetype;
     private User userByOwnerId;
     private User userByCreatorId;
     private Business business;
     private String about;
     private String pageUrl;
     private String profilePicture;
     private Boolean isOrganization;
     private Boolean isEvent;
     private Boolean isCommunity;
     private Date createdtime;
     private Date updatedtime;
     private Set pageuserlikeses = new HashSet(0);
     private Set topcommunitysuggestions = new HashSet(0);

    public Page() {
    }

	
    public Page(Pagetype pagetype, User userByOwnerId, User userByCreatorId, Date createdtime, Date updatedtime) {
        this.pagetype = pagetype;
        this.userByOwnerId = userByOwnerId;
        this.userByCreatorId = userByCreatorId;
        this.createdtime = createdtime;
        this.updatedtime = updatedtime;
    }
    public Page(Pagetype pagetype, User userByOwnerId, User userByCreatorId, Business business, String about, String pageUrl, String profilePicture, Boolean isOrganization, Boolean isEvent, Boolean isCommunity, Date createdtime, Date updatedtime, Set pageuserlikeses) {
       this.pagetype = pagetype;
       this.userByOwnerId = userByOwnerId;
       this.userByCreatorId = userByCreatorId;
       this.business = business;
       this.about = about;
       this.pageUrl = pageUrl;
       this.profilePicture = profilePicture;
       this.isOrganization = isOrganization;
       this.isEvent = isEvent;
       this.isCommunity = isCommunity;
       this.createdtime = createdtime;
       this.updatedtime = updatedtime;
       this.pageuserlikeses = pageuserlikeses;
    }
   
    public Integer getPageId() {
        return this.pageId;
    }
    
    public void setPageId(Integer pageId) {
        this.pageId = pageId;
    }
    public Pagetype getPagetype() {
        return this.pagetype;
    }
    
    public void setPagetype(Pagetype pagetype) {
        this.pagetype = pagetype;
    }
    public User getUserByOwnerId() {
        return this.userByOwnerId;
    }
    
    public void setUserByOwnerId(User userByOwnerId) {
        this.userByOwnerId = userByOwnerId;
    }
    public User getUserByCreatorId() {
        return this.userByCreatorId;
    }
    
    public void setUserByCreatorId(User userByCreatorId) {
        this.userByCreatorId = userByCreatorId;
    }
    public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public String getPageUrl() {
        return this.pageUrl;
    }
    
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }
    public String getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }
    public Boolean getIsOrganization() {
        return this.isOrganization;
    }
    
    public void setIsOrganization(Boolean isOrganization) {
        this.isOrganization = isOrganization;
    }
    public Boolean getIsEvent() {
        return this.isEvent;
    }
    
    public void setIsEvent(Boolean isEvent) {
        this.isEvent = isEvent;
    }
    public Boolean getIsCommunity() {
        return this.isCommunity;
    }
    
    public void setIsCommunity(Boolean isCommunity) {
        this.isCommunity = isCommunity;
    }
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }
    public Set getPageuserlikeses() {
        return this.pageuserlikeses;
    }
    
    public void setPageuserlikeses(Set pageuserlikeses) {
        this.pageuserlikeses = pageuserlikeses;
    }


	/**
	 * @param topcommunitysuggestions the topcommunitysuggestions to set
	 */
	public void setTopcommunitysuggestions(Set topcommunitysuggestions) {
		this.topcommunitysuggestions = topcommunitysuggestions;
	}


	/**
	 * @return the topcommunitysuggestions
	 */
	public Set getTopcommunitysuggestions() {
		return topcommunitysuggestions;
	}




}


