package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Pageuserlikes generated by hbm2java
 */
public class Pageuserlikes  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer pageUserLikesId;
     private User user;
     private Page page;
     private Notificationpermission notificationpermission;
     private Boolean isFavorite;
     private Boolean isFollowing;
     private Boolean isLike;
     private Boolean isVisited;
     private Boolean isProfileHidden;
     private Boolean isProfileDetailsHidden;
     private String displayName;
     private Date createdtime;
     private Date updatedtime;

    public Pageuserlikes() {
    }

	
    public Pageuserlikes(User user, Page page, Notificationpermission notificationpermission, Date createdtime, Date updatedtime) {
        this.user = user;
        this.page = page;
        this.notificationpermission = notificationpermission;
        this.createdtime = createdtime;
        this.updatedtime = updatedtime;
    }
    public Pageuserlikes(User user, Page page, Notificationpermission notificationpermission, Boolean isFavorite, Boolean isFollowing, Boolean isLike, Boolean isVisited, Boolean isProfileHidden, Boolean isProfileDetailsHidden, String displayName, Date createdtime, Date updatedtime) {
       this.user = user;
       this.page = page;
       this.notificationpermission = notificationpermission;
       this.isFavorite = isFavorite;
       this.isFollowing = isFollowing;
       this.isLike = isLike;
       this.isVisited = isVisited;
       this.isProfileHidden = isProfileHidden;
       this.isProfileDetailsHidden = isProfileDetailsHidden;
       this.displayName = displayName;
       this.createdtime = createdtime;
       this.updatedtime = updatedtime;
    }
   
    public Integer getPageUserLikesId() {
        return this.pageUserLikesId;
    }
    
    public void setPageUserLikesId(Integer pageUserLikesId) {
        this.pageUserLikesId = pageUserLikesId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Page getPage() {
        return this.page;
    }
    
    public void setPage(Page page) {
        this.page = page;
    }
    public Notificationpermission getNotificationpermission() {
        return this.notificationpermission;
    }
    
    public void setNotificationpermission(Notificationpermission notificationpermission) {
        this.notificationpermission = notificationpermission;
    }
    public Boolean getIsFavorite() {
        return this.isFavorite;
    }
    
    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }
    public Boolean getIsFollowing() {
        return this.isFollowing;
    }
    
    public void setIsFollowing(Boolean isFollowing) {
        this.isFollowing = isFollowing;
    }
    public Boolean getIsLike() {
        return this.isLike;
    }
    
    public void setIsLike(Boolean isLike) {
        this.isLike = isLike;
    }
    public Boolean getIsVisited() {
        return this.isVisited;
    }
    
    public void setIsVisited(Boolean isVisited) {
        this.isVisited = isVisited;
    }
    public Boolean getIsProfileHidden() {
        return this.isProfileHidden;
    }
    
    public void setIsProfileHidden(Boolean isProfileHidden) {
        this.isProfileHidden = isProfileHidden;
    }
    public Boolean getIsProfileDetailsHidden() {
        return this.isProfileDetailsHidden;
    }
    
    public void setIsProfileDetailsHidden(Boolean isProfileDetailsHidden) {
        this.isProfileDetailsHidden = isProfileDetailsHidden;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }




}


