package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Page generated by hbm2java
 */
public class PopularCommunity  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer communityId;
     private Pagetype pagetype;
     private String about;
     private String pageUrl;
     private String profilePicture;
     private String abbreviation;
     private String home;
     private Date createdTime;
     private Date updatedTime;
    
     
    // private List<PageFunboard> funboards;

    public PopularCommunity() {
    }

	
    public PopularCommunity(Pagetype pagetype, Date createdTime, Date updatedTime) {
        this.setPagetype(pagetype);
        this.createdTime = createdTime;
        this.updatedTime = updatedTime;
    }
    public PopularCommunity(Pagetype pagetype, String about, String pageUrl, String profilePicture,Date createdTime, Date updatedTime ) {
       this.setPagetype(pagetype);
       this.about = about;
       this.pageUrl = pageUrl;
       this.profilePicture = profilePicture;
       this.createdTime = createdTime;
       this.updatedTime = updatedTime;
      
    }
   
    public Integer getCommunityId() {
        return this.communityId;
    }
    
    public void setCommunityId(Integer communityId) {
        this.communityId = communityId;
    }
   
    public String getAbout() {
        return this.about;
    }
    
    public void setAbout(String about) {
        this.about = about;
    }
    public String getPageUrl() {
        return this.pageUrl;
    }
    
    public void setPageUrl(String pageUrl) {
        this.pageUrl = pageUrl;
    }
    public String getProfilePicture() {
        return this.profilePicture;
    }
    
    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }
   
    public Date getCreatedTime() {
        return this.createdTime;
    }
    
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
    public Date getUpdatedTime() {
        return this.updatedTime;
    }
    
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }


	public Pagetype getPagetype() {
		return pagetype;
	}


	public void setPagetype(Pagetype pagetype) {
		this.pagetype = pagetype;
	}


	public String getAbbreviation() {
		return abbreviation;
	}


	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}


	public String getHome() {
		return home;
	}


	public void setHome(String home) {
		this.home = home;
	}
}


