package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Profiletype generated by hbm2java
 */
public class Profiletype  implements java.io.Serializable {


     private Integer profileTypeId;
     private String userType;
     private Set users = new HashSet(0);

    public Profiletype() {
    }

	
    public Profiletype(String userType) {
        this.userType = userType;
    }
    public Profiletype(String userType, Set users) {
       this.userType = userType;
       this.users = users;
    }
   
    public Integer getProfileTypeId() {
        return this.profileTypeId;
    }
    
    public void setProfileTypeId(Integer profileTypeId) {
        this.profileTypeId = profileTypeId;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public Set getUsers() {
        return this.users;
    }
    
    public void setUsers(Set users) {
        this.users = users;
    }




}


