package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usercontactsgroupmap generated by hbm2java
 */
public class Usercontactsgroupmap  implements java.io.Serializable {


     private Integer id;
     private Usercontacts usercontacts;
     private Usergroups usergroups;
     private Date createdtime;
     private Date updatedtime;

    public Usercontactsgroupmap() {
    }

    public Usercontactsgroupmap(Usercontacts usercontacts, Usergroups usergroups, Date createdtime, Date updatedtime) {
       this.usercontacts = usercontacts;
       this.usergroups = usergroups;
       this.createdtime = createdtime;
       this.updatedtime = updatedtime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usercontacts getUsercontacts() {
        return this.usercontacts;
    }
    
    public void setUsercontacts(Usercontacts usercontacts) {
        this.usercontacts = usercontacts;
    }
    public Usergroups getUsergroups() {
        return this.usergroups;
    }
    
    public void setUsergroups(Usergroups usergroups) {
        this.usergroups = usergroups;
    }
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }




}


