package com.jeeyoh.persistence.domain;
// Generated Nov 30, 2013 1:10:08 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usernondealsuggestion generated by hbm2java
 */
public class Usernondealsuggestion  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer suggestionId;
     private User user;
     private User userContact;
     private Business business;
     private Boolean isChecked;
     private Boolean isRelevant;
     private String suggestionType;
     private Date createdtime;
     private Date updatedtime;
     private Date suggestedTime;

    public Usernondealsuggestion() {
    }

	
    public Usernondealsuggestion(User user, Business business, Date createdtime, Date updatedtime) {
        this.user = user;
        this.business = business;
        this.createdtime = createdtime;
        this.updatedtime = updatedtime;
    }
    public Usernondealsuggestion(User user, Business business, Boolean isChecked, Boolean isRelevant, Date createdtime, Date updatedtime) {
       this.user = user;
       this.business = business;
       this.isChecked = isChecked;
       this.isRelevant = isRelevant;
       this.createdtime = createdtime;
       this.updatedtime = updatedtime;
    }
   
    public Integer getSuggestionId() {
        return this.suggestionId;
    }
    
    public void setSuggestionId(Integer suggestionId) {
        this.suggestionId = suggestionId;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    /**
	 * @return the userContact
	 */
	public User getUserContact() {
		return userContact;
	}


	/**
	 * @param userContact the userContact to set
	 */
	public void setUserContact(User userContact) {
		this.userContact = userContact;
	}


	public Business getBusiness() {
        return this.business;
    }
    
    public void setBusiness(Business business) {
        this.business = business;
    }
    public Boolean getIsChecked() {
        return this.isChecked;
    }
    
    public void setIsChecked(Boolean isChecked) {
        this.isChecked = isChecked;
    }
    public Boolean getIsRelevant() {
        return this.isRelevant;
    }
    
    public void setIsRelevant(Boolean isRelevant) {
        this.isRelevant = isRelevant;
    }
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }


	/**
	 * @param suggestionType the suggestionType to set
	 */
	public void setSuggestionType(String suggestionType) {
		this.suggestionType = suggestionType;
	}


	/**
	 * @return the suggestionType
	 */
	public String getSuggestionType() {
		return suggestionType;
	}


	/**
	 * @return the suggestedTime
	 */
	public Date getSuggestedTime() {
		return suggestedTime;
	}


	/**
	 * @param suggestedTime the suggestedTime to set
	 */
	public void setSuggestedTime(Date suggestedTime) {
		this.suggestedTime = suggestedTime;
	}




}


