package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usergroups generated by hbm2java
 */
public class Usergroups  implements java.io.Serializable {


     private Integer userGroupId;
     private String userGroupName;
     private String description;
     private Date createdtime;
     private Date updatedtime;
     private Set usercontactsgroupmaps = new HashSet(0);

    public Usergroups() {
    }

	
    public Usergroups(Date createdtime, Date updatedtime) {
        this.createdtime = createdtime;
        this.updatedtime = updatedtime;
    }
    public Usergroups(String userGroupName, String description, Date createdtime, Date updatedtime, Set usercontactsgroupmaps) {
       this.userGroupName = userGroupName;
       this.description = description;
       this.createdtime = createdtime;
       this.updatedtime = updatedtime;
       this.usercontactsgroupmaps = usercontactsgroupmaps;
    }
   
    public Integer getUserGroupId() {
        return this.userGroupId;
    }
    
    public void setUserGroupId(Integer userGroupId) {
        this.userGroupId = userGroupId;
    }
    public String getUserGroupName() {
        return this.userGroupName;
    }
    
    public void setUserGroupName(String userGroupName) {
        this.userGroupName = userGroupName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Date getCreatedtime() {
        return this.createdtime;
    }
    
    public void setCreatedtime(Date createdtime) {
        this.createdtime = createdtime;
    }
    public Date getUpdatedtime() {
        return this.updatedtime;
    }
    
    public void setUpdatedtime(Date updatedtime) {
        this.updatedtime = updatedtime;
    }
    public Set getUsercontactsgroupmaps() {
        return this.usercontactsgroupmaps;
    }
    
    public void setUsercontactsgroupmaps(Set usercontactsgroupmaps) {
        this.usercontactsgroupmaps = usercontactsgroupmaps;
    }




}


