package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Ybusinessregionmap generated by hbm2java
 */
public class Ybusinessregionmap  implements java.io.Serializable {


     private Integer id;
     private Yregion yregion;
     private Ybusiness ybusiness;

    public Ybusinessregionmap() {
    }

    public Ybusinessregionmap(Yregion yregion, Ybusiness ybusiness) {
       this.yregion = yregion;
       this.ybusiness = ybusiness;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Yregion getYregion() {
        return this.yregion;
    }
    
    public void setYregion(Yregion yregion) {
        this.yregion = yregion;
    }
    public Ybusiness getYbusiness() {
        return this.ybusiness;
    }
    
    public void setYbusiness(Ybusiness ybusiness) {
        this.ybusiness = ybusiness;
    }




}


