package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Ybusinesscategorymap generated by hbm2java
 */
public class Ybusinesscategorymap  implements java.io.Serializable {


     private Integer id;
     private Ycategoryfilter ycategoryfilter;
     private Ybusiness ybusiness;

    public Ybusinesscategorymap() {
    }

    public Ybusinesscategorymap(Ycategoryfilter ycategoryfilter, Ybusiness ybusiness) {
       this.ycategoryfilter = ycategoryfilter;
       this.ybusiness = ybusiness;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ycategoryfilter getYcategoryfilter() {
        return this.ycategoryfilter;
    }
    
    public void setYcategoryfilter(Ycategoryfilter ycategoryfilter) {
        this.ycategoryfilter = ycategoryfilter;
    }
    public Ybusiness getYbusiness() {
        return this.ybusiness;
    }
    
    public void setYbusiness(Ybusiness ybusiness) {
        this.ybusiness = ybusiness;
    }




}


