package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ybusiness generated by hbm2java
 */
public class Ybusiness  implements java.io.Serializable {


     private Integer id;
     private String businessId;
     private Boolean isClaimed;
     private Boolean isClosed;
     private String name;
     private String url;
     private String imageUrl;
     private String mobileUrl;
     private String phone;
     private String displayPhone;
     private String reviewCount;
     private Long distance;
     private Double rating;
     private String ratingImgUrl;
     private String ratingSmallImgUrl;
     private String ratingLargeImgUrl;
     private String snippetText;
     private String snippetImageUrl;
     private String menuProvider;
     private Long menuProviderDate;
     private String crossStreets;
     private String city;
     private String displayAddress;
     private String postalCode;
     private String countryCode;
     private String address;
     private String stateCode;
     private String neighborhoods;
     private Set ydeals = new HashSet(0);
     private Set ybusinessregionmaps = new HashSet(0);
     private Set ybusinesscategorymaps = new HashSet(0);
     private Set yreviews = new HashSet(0);

    public Ybusiness() {
    }

    public Ybusiness(String businessId, Boolean isClaimed, Boolean isClosed, String name, String url, String mobileUrl, String phone, String displayPhone, String reviewCount, Long distance, Double rating, String ratingImgUrl, String ratingSmallImgUrl, String ratingLargeImgUrl, String snippetText, String snippetImageUrl, String menuProvider, Long menuProviderDate, String crossStreets, String city, String displayAddress, String postalCode, String countryCode, String address, String stateCode, String neighborhoods, Set ydeals, Set ybusinessregionmaps, Set ybusinesscategorymaps, Set yreviews) {
       this.businessId = businessId;
       this.isClaimed = isClaimed;
       this.isClosed = isClosed;
       this.name = name;
       this.url = url;
       this.mobileUrl = mobileUrl;
       this.phone = phone;
       this.displayPhone = displayPhone;
       this.reviewCount = reviewCount;
       this.distance = distance;
       this.rating = rating;
       this.ratingImgUrl = ratingImgUrl;
       this.ratingSmallImgUrl = ratingSmallImgUrl;
       this.ratingLargeImgUrl = ratingLargeImgUrl;
       this.snippetText = snippetText;
       this.snippetImageUrl = snippetImageUrl;
       this.menuProvider = menuProvider;
       this.menuProviderDate = menuProviderDate;
       this.crossStreets = crossStreets;
       this.city = city;
       this.displayAddress = displayAddress;
       this.postalCode = postalCode;
       this.countryCode = countryCode;
       this.address = address;
       this.stateCode = stateCode;
       this.neighborhoods = neighborhoods;
       this.ydeals = ydeals;
       this.ybusinessregionmaps = ybusinessregionmaps;
       this.ybusinesscategorymaps = ybusinesscategorymaps;
       this.yreviews = yreviews;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBusinessId() {
        return this.businessId;
    }
    
    public void setBusinessId(String businessId) {
        this.businessId = businessId;
    }
    public Boolean getIsClaimed() {
        return this.isClaimed;
    }
    
    public void setIsClaimed(Boolean isClaimed) {
        this.isClaimed = isClaimed;
    }
    public Boolean getIsClosed() {
        return this.isClosed;
    }
    
    public void setIsClosed(Boolean isClosed) {
        this.isClosed = isClosed;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getMobileUrl() {
        return this.mobileUrl;
    }
    
    public void setMobileUrl(String mobileUrl) {
        this.mobileUrl = mobileUrl;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getDisplayPhone() {
        return this.displayPhone;
    }
    
    public void setDisplayPhone(String displayPhone) {
        this.displayPhone = displayPhone;
    }
    public String getReviewCount() {
        return this.reviewCount;
    }
    
    public void setReviewCount(String reviewCount) {
        this.reviewCount = reviewCount;
    }
    public Long getDistance() {
        return this.distance;
    }
    
    public void setDistance(Long distance) {
        this.distance = distance;
    }
    public Double getRating() {
        return this.rating;
    }
    
    public void setRating(Double rating) {
        this.rating = rating;
    }
    public String getRatingImgUrl() {
        return this.ratingImgUrl;
    }
    
    public void setRatingImgUrl(String ratingImgUrl) {
        this.ratingImgUrl = ratingImgUrl;
    }
    public String getRatingSmallImgUrl() {
        return this.ratingSmallImgUrl;
    }
    
    public void setRatingSmallImgUrl(String ratingSmallImgUrl) {
        this.ratingSmallImgUrl = ratingSmallImgUrl;
    }
    public String getRatingLargeImgUrl() {
        return this.ratingLargeImgUrl;
    }
    
    public void setRatingLargeImgUrl(String ratingLargeImgUrl) {
        this.ratingLargeImgUrl = ratingLargeImgUrl;
    }
    public String getSnippetText() {
        return this.snippetText;
    }
    
    public void setSnippetText(String snippetText) {
        this.snippetText = snippetText;
    }
    public String getSnippetImageUrl() {
        return this.snippetImageUrl;
    }
    
    public void setSnippetImageUrl(String snippetImageUrl) {
        this.snippetImageUrl = snippetImageUrl;
    }
    public String getMenuProvider() {
        return this.menuProvider;
    }
    
    public void setMenuProvider(String menuProvider) {
        this.menuProvider = menuProvider;
    }
    public Long getMenuProviderDate() {
        return this.menuProviderDate;
    }
    
    public void setMenuProviderDate(Long menuProviderDate) {
        this.menuProviderDate = menuProviderDate;
    }
    public String getCrossStreets() {
        return this.crossStreets;
    }
    
    public void setCrossStreets(String crossStreets) {
        this.crossStreets = crossStreets;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getDisplayAddress() {
        return this.displayAddress;
    }
    
    public void setDisplayAddress(String displayAddress) {
        this.displayAddress = displayAddress;
    }
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getStateCode() {
        return this.stateCode;
    }
    
    public void setStateCode(String stateCode) {
        this.stateCode = stateCode;
    }
    public String getNeighborhoods() {
        return this.neighborhoods;
    }
    
    public void setNeighborhoods(String neighborhoods) {
        this.neighborhoods = neighborhoods;
    }
    public Set getYdeals() {
        return this.ydeals;
    }
    
    public void setYdeals(Set ydeals) {
        this.ydeals = ydeals;
    }
    public Set getYbusinessregionmaps() {
        return this.ybusinessregionmaps;
    }
    
    public void setYbusinessregionmaps(Set ybusinessregionmaps) {
        this.ybusinessregionmaps = ybusinessregionmaps;
    }
    public Set getYbusinesscategorymaps() {
        return this.ybusinesscategorymaps;
    }
    
    public void setYbusinesscategorymaps(Set ybusinesscategorymaps) {
        this.ybusinesscategorymaps = ybusinesscategorymaps;
    }
    public Set getYreviews() {
        return this.yreviews;
    }
    
    public void setYreviews(Set yreviews) {
        this.yreviews = yreviews;
    }

	public String getImageUrl() {
		return imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}




}


