package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Ybusinesstype generated by hbm2java
 */
public class Ybusinesstype  implements java.io.Serializable {


     private Integer businessTypeId;
     private String businessType;
     private String description;

    public Ybusinesstype() {
    }

    public Ybusinesstype(String businessType, String description) {
       this.businessType = businessType;
       this.description = description;
    }
   
    public Integer getBusinessTypeId() {
        return this.businessTypeId;
    }
    
    public void setBusinessTypeId(Integer businessTypeId) {
        this.businessTypeId = businessTypeId;
    }
    public String getBusinessType() {
        return this.businessType;
    }
    
    public void setBusinessType(String businessType) {
        this.businessType = businessType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


