package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ycategoryfilter generated by hbm2java
 */
public class Ycategoryfilter  implements java.io.Serializable {


     private Integer id;
     private Ycategoryfilter ycategoryfilter;
     private String category;
     private String value;
     private Set ybusinesscategorymaps = new HashSet(0);
     private Set ycategoryfilters = new HashSet(0);

    public Ycategoryfilter() {
    }

	
    public Ycategoryfilter(Ycategoryfilter ycategoryfilter) {
        this.ycategoryfilter = ycategoryfilter;
    }
    public Ycategoryfilter(Ycategoryfilter ycategoryfilter, String category, String value, Set ybusinesscategorymaps, Set ycategoryfilters) {
       this.ycategoryfilter = ycategoryfilter;
       this.category = category;
       this.value = value;
       this.ybusinesscategorymaps = ybusinesscategorymaps;
       this.ycategoryfilters = ycategoryfilters;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ycategoryfilter getYcategoryfilter() {
        return this.ycategoryfilter;
    }
    
    public void setYcategoryfilter(Ycategoryfilter ycategoryfilter) {
        this.ycategoryfilter = ycategoryfilter;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }
    public Set getYbusinesscategorymaps() {
        return this.ybusinesscategorymaps;
    }
    
    public void setYbusinesscategorymaps(Set ybusinesscategorymaps) {
        this.ybusinesscategorymaps = ybusinesscategorymaps;
    }
    public Set getYcategoryfilters() {
        return this.ycategoryfilters;
    }
    
    public void setYcategoryfilters(Set ycategoryfilters) {
        this.ycategoryfilters = ycategoryfilters;
    }




}


