package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ydeal generated by hbm2java
 */
public class Ydeal  implements java.io.Serializable {


     private Integer id;
     private Ybusiness ybusiness;
     private String dealId;
     private String dealTitle;
     private String dealUrl;
     private String dealImageUrl;
     private String currencyCode;
     private String dealStartTime;
     private String dealEndTime;
     private Boolean isPopular;
     private String additionalDeals;
     private String impRestrictions;
     private String additionalRestrictions;
     private Set ydealoptions = new HashSet(0);

    public Ydeal() {
    }

	
    public Ydeal(Ybusiness ybusiness) {
        this.ybusiness = ybusiness;
    }
    public Ydeal(Ybusiness ybusiness, String dealId, String dealTitle, String dealUrl, String dealImageUrl, String currencyCode, String dealStartTime, String dealEndTime, Boolean isPopular, String additionalDeals, String impRestrictions, String additionalRestrictions, Set ydealoptions) {
       this.ybusiness = ybusiness;
       this.dealId = dealId;
       this.dealTitle = dealTitle;
       this.dealUrl = dealUrl;
       this.dealImageUrl = dealImageUrl;
       this.currencyCode = currencyCode;
       this.dealStartTime = dealStartTime;
       this.dealEndTime = dealEndTime;
       this.isPopular = isPopular;
       this.additionalDeals = additionalDeals;
       this.impRestrictions = impRestrictions;
       this.additionalRestrictions = additionalRestrictions;
       this.ydealoptions = ydealoptions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ybusiness getYbusiness() {
        return this.ybusiness;
    }
    
    public void setYbusiness(Ybusiness ybusiness) {
        this.ybusiness = ybusiness;
    }
    public String getDealId() {
        return this.dealId;
    }
    
    public void setDealId(String dealId) {
        this.dealId = dealId;
    }
    public String getDealTitle() {
        return this.dealTitle;
    }
    
    public void setDealTitle(String dealTitle) {
        this.dealTitle = dealTitle;
    }
    public String getDealUrl() {
        return this.dealUrl;
    }
    
    public void setDealUrl(String dealUrl) {
        this.dealUrl = dealUrl;
    }
    public String getDealImageUrl() {
        return this.dealImageUrl;
    }
    
    public void setDealImageUrl(String dealImageUrl) {
        this.dealImageUrl = dealImageUrl;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getDealStartTime() {
        return this.dealStartTime;
    }
    
    public void setDealStartTime(String dealStartTime) {
        this.dealStartTime = dealStartTime;
    }
    public String getDealEndTime() {
        return this.dealEndTime;
    }
    
    public void setDealEndTime(String dealEndTime) {
        this.dealEndTime = dealEndTime;
    }
    public Boolean getIsPopular() {
        return this.isPopular;
    }
    
    public void setIsPopular(Boolean isPopular) {
        this.isPopular = isPopular;
    }
    public String getAdditionalDeals() {
        return this.additionalDeals;
    }
    
    public void setAdditionalDeals(String additionalDeals) {
        this.additionalDeals = additionalDeals;
    }
    public String getImpRestrictions() {
        return this.impRestrictions;
    }
    
    public void setImpRestrictions(String impRestrictions) {
        this.impRestrictions = impRestrictions;
    }
    public String getAdditionalRestrictions() {
        return this.additionalRestrictions;
    }
    
    public void setAdditionalRestrictions(String additionalRestrictions) {
        this.additionalRestrictions = additionalRestrictions;
    }
    public Set getYdealoptions() {
        return this.ydealoptions;
    }
    
    public void setYdealoptions(Set ydealoptions) {
        this.ydealoptions = ydealoptions;
    }




}


