package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ydealoption generated by hbm2java
 */
public class Ydealoption  implements java.io.Serializable {


     private Integer id;
     private Ydeal ydeal;
     private String title;
     private String purchaseUrl;
     private Long price;
     private String formattedPrice;
     private Long originalPrice;
     private String formattedOriginalPrice;
     private Boolean isLimitedQuantity;
     private String remainingCount;
     //private Set ygiftoptionmaps = new HashSet(0);

    public Ydealoption() {
    }

	
    public Ydealoption(Ydeal ydeal) {
        this.ydeal = ydeal;
    }
    public Ydealoption(Ydeal ydeal, String title, String purchaseUrl, Long price, String formattedPrice, Long originalPrice, String formattedOriginalPrice, Boolean isLimitedQuantity, String remainingCount, Set ygiftoptionmaps) {
       this.ydeal = ydeal;
       this.title = title;
       this.purchaseUrl = purchaseUrl;
       this.price = price;
       this.formattedPrice = formattedPrice;
       this.originalPrice = originalPrice;
       this.formattedOriginalPrice = formattedOriginalPrice;
       this.isLimitedQuantity = isLimitedQuantity;
       this.remainingCount = remainingCount;
       //this.ygiftoptionmaps = ygiftoptionmaps;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ydeal getYdeal() {
        return this.ydeal;
    }
    
    public void setYdeal(Ydeal ydeal) {
        this.ydeal = ydeal;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getPurchaseUrl() {
        return this.purchaseUrl;
    }
    
    public void setPurchaseUrl(String purchaseUrl) {
        this.purchaseUrl = purchaseUrl;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public String getFormattedPrice() {
        return this.formattedPrice;
    }
    
    public void setFormattedPrice(String formattedPrice) {
        this.formattedPrice = formattedPrice;
    }
    public Long getOriginalPrice() {
        return this.originalPrice;
    }
    
    public void setOriginalPrice(Long originalPrice) {
        this.originalPrice = originalPrice;
    }
    public String getFormattedOriginalPrice() {
        return this.formattedOriginalPrice;
    }
    
    public void setFormattedOriginalPrice(String formattedOriginalPrice) {
        this.formattedOriginalPrice = formattedOriginalPrice;
    }
    public Boolean getIsLimitedQuantity() {
        return this.isLimitedQuantity;
    }
    
    public void setIsLimitedQuantity(Boolean isLimitedQuantity) {
        this.isLimitedQuantity = isLimitedQuantity;
    }
    public String getRemainingCount() {
        return this.remainingCount;
    }
    
    public void setRemainingCount(String remainingCount) {
        this.remainingCount = remainingCount;
    }
    /*public Set getYgiftoptionmaps() {
        return this.ygiftoptionmaps;
    }
    
    public void setYgiftoptionmaps(Set ygiftoptionmaps) {
        this.ygiftoptionmaps = ygiftoptionmaps;
    }*/




}


