package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Ygiftcertificate generated by hbm2java
 */
public class Ygiftcertificate  implements java.io.Serializable {


     private int id;
     private String giftCertificateId;
     private String giftCertificateUrl;
     private String giftCertificateImageUrl;
     private String currencyCode;
     private String unusedBalances;
     private Set ygiftoptionmaps = new HashSet(0);

    public Ygiftcertificate() {
    }

	
    public Ygiftcertificate(int id) {
        this.id = id;
    }
    public Ygiftcertificate(int id, String giftCertificateId, String giftCertificateUrl, String giftCertificateImageUrl, String currencyCode, String unusedBalances, Set ygiftoptionmaps) {
       this.id = id;
       this.giftCertificateId = giftCertificateId;
       this.giftCertificateUrl = giftCertificateUrl;
       this.giftCertificateImageUrl = giftCertificateImageUrl;
       this.currencyCode = currencyCode;
       this.unusedBalances = unusedBalances;
       this.ygiftoptionmaps = ygiftoptionmaps;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getGiftCertificateId() {
        return this.giftCertificateId;
    }
    
    public void setGiftCertificateId(String giftCertificateId) {
        this.giftCertificateId = giftCertificateId;
    }
    public String getGiftCertificateUrl() {
        return this.giftCertificateUrl;
    }
    
    public void setGiftCertificateUrl(String giftCertificateUrl) {
        this.giftCertificateUrl = giftCertificateUrl;
    }
    public String getGiftCertificateImageUrl() {
        return this.giftCertificateImageUrl;
    }
    
    public void setGiftCertificateImageUrl(String giftCertificateImageUrl) {
        this.giftCertificateImageUrl = giftCertificateImageUrl;
    }
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }
    public String getUnusedBalances() {
        return this.unusedBalances;
    }
    
    public void setUnusedBalances(String unusedBalances) {
        this.unusedBalances = unusedBalances;
    }
    public Set getYgiftoptionmaps() {
        return this.ygiftoptionmaps;
    }
    
    public void setYgiftoptionmaps(Set ygiftoptionmaps) {
        this.ygiftoptionmaps = ygiftoptionmaps;
    }




}


