package com.jeeyoh.persistence.domain;
// Generated Oct 10, 2013 9:08:11 AM by Hibernate Tools 3.2.1.GA



/**
 * Ygiftoptionmap generated by hbm2java
 */
public class Ygiftoptionmap  implements java.io.Serializable {


     private Integer id;
     private Ygiftcertificate ygiftcertificate;
     private Ydealoption ydealoption;

    public Ygiftoptionmap() {
    }

    public Ygiftoptionmap(Ygiftcertificate ygiftcertificate, Ydealoption ydealoption) {
       this.ygiftcertificate = ygiftcertificate;
       this.ydealoption = ydealoption;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Ygiftcertificate getYgiftcertificate() {
        return this.ygiftcertificate;
    }
    
    public void setYgiftcertificate(Ygiftcertificate ygiftcertificate) {
        this.ygiftcertificate = ygiftcertificate;
    }
    public Ydealoption getYdealoption() {
        return this.ydealoption;
    }
    
    public void setYdealoption(Ydealoption ydealoption) {
        this.ydealoption = ydealoption;
    }




}


